### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by fredRos** [bat/bat#117]
Can the chain recover if NaN comes up? For example with negative expectation in a poisson process. If not, let's abort

**Comment by greenwald** [comment]
If NaN is the posterior for the proposal, then yes, the chain recovers---or correctly put: the chain never fails, since the point is not accepted. This can easily happen if one has naively set parameter ranges and used factorized priors, and so the chain can easily end up in a region that is in fact incalculable. Ideally one would use priors to properly avoid these regions; but I don't think it's necessary to fail.

If NaN is the current (accepted) posterior, the chain still recover, as long as a point is proposed that has a real posterior. This should not happen, though, since a check is made that the initial point produces a real posterior, and proposed points evaluating to NaN will not be accepted.
