### ISSUE TITLE
BCTH1Prior:  Copy Prior histogram instead of using the reference?

### ISSUE THREAD

**Issue by tquante** [bat/bat#174]
Dear Developers,

I need to use the BCTH1Prior and noticed that it only uses the reference of the the given histogram. Would it be possible to copy the used histogram for internal usage? Because in the current version it is impossible to generate a BCTH1Prior inside another function because the histogram goes out of scope which lead to a segfault error if you use this prior. 

Best Regards 

Thomas Quante

**Comment by fredRos** [comment]
As far as I remember - @greenwald corrects me if I'm wrong - we use a `TH1&` to make use of ROOT's weird inheritance scheme such that a float and a double histogram can be used with the same code. 

> Would it be possible to copy the used histogram for internal usage?

Unfortunately, you can't simply create an independent copy because the assignment operator is (judiciously?) declared private.

> Because in the current version it is impossible to generate a BCTH1Prior inside another function because the histogram goes out of scope which lead to a segfault error if you use this prior. 

To work around this problem, of course you need to keep a reference to the histogram manually. I know this is cumbersome but you can do it if you really want to, and it may be easier with C++11 using a unique or shared pointer to the histogram

```c++
std::pair<TH1D, BCTH1Prior> Prior factory()
{
    TH1D* hist = new TH1D(...);
    BCTH1Prior prior(hist);
    return std::make_pair<TH1D*, BCTH1Prior>(hist, prior);
}
```

**Comment by tquante** [comment]
The TH1 copy constructor need to be private because there is neither an object nor a vtable, which can be used to look for the right ctor. Hence the virtual Clone() function was introduced which can be used for this purpose. Probably you could store the prior in a unique_ptr<TH1> and use a reference to the object for further usage? In this case the object gets destroyed if the BCPrior goes out of scope and it should not have any performance impact.

**Comment by greenwald** [comment]
To be honest, I can't think of a reason why I used a reference instead of a pointer, except to prevent the possibility of creating a `BCTH1DPrior` with a null pointer or to prevent having to check always against the pointer being null.

We certainly can't just copy the object into a member `TH1`, since this would slice whatever is copied. I would _happily_ replace it all with a smart pointer---but unfortunately we are stuck in the pre-c++11 days.

A middle ground would be to make the decision that the `BCTH1DPrior` takes ownership of the `TH1` and therefore deletes it at destruction. Then you could pass a pointer to a new `TH1D` to the prior as in @fredRos's code above, but not need to track. I'm not opposed to this solution, since in the situation where a single histogram is shared amongst several priors, the user is in a better place to clone it and pass it to each prior than BAT is.

**Comment by oschulz** [comment]
@fredRos : Since you marked this wontfix - should we close this or not?

**Comment by fredRos** [comment]
> To be honest, I can't think of a reason why I used a reference instead of a pointer, except to prevent the possibility of creating a BCTH1Prior with a null pointer or to prevent having to check always against the pointer being null.

These two reasons were exactly our motivation to use a reference instead of a pointer.

> We certainly can't just copy the object into a member TH1, since this would slice whatever is copied. I would happily replace it all with a smart pointer---but unfortunately we are stuck in the pre-c++11 days.

I agree, I would also happily use smart pointers. We have agreed to move 1.0 out with C++03. Else we should rewrite many parts of the code for consistency with C++11. But this "management" decision should not lead to inconvenience for the user (only for the developer :smile:) 

@tquante Do you see a good use case for sharing a single instance of `TH1` among multiple `BCTH1Prior` objects? If this is rare, why not just make a copy upon construction of `BCTH1Prior`. Typical footprints of 1D histograms are very small, so the copy doesn't matter and we save ourselves and the user trouble.

**Comment by tquante** [comment]
> @tquante Do you see a good use case for sharing a single instance of TH1 among multiple BCTH1Prior objects? If this is rare, why not just make a copy upon construction of BCTH1Prior. Typical footprints of 1D histograms are very small, so the copy doesn't matter and we save ourselves and the user trouble.

As far as I understand the prior will be calculated for each parameter separately. Even in use cases this will only save the computing time for copying the input histogram. I would consider this as almost non existing improvement compared to the run time of a markov chain. This will only matter in a case were thousands of priors are needed, which consumes a lot of memory.

Another typical problem is the root ownership which will lead to a segfault if someone is not aware of that the histogram is owned by a TFile, which will delete the histogram upon closing. Also this behavior is not consistent with other interfaces like BCHistogramFitter which will copy the histogram, hence not showing the tfile closing problem.

**Comment by fredRos** [comment]
> As far as I understand the prior will be calculated for each parameter separately. Even in use cases this will only save the computing time for copying the input histogram. I would consider this as almost non existing improvement compared to the run time of a markov chain. This will only matter in a case were thousands of priors are needed, which consumes a lot of memory.

For thousands of parameters, the random walk is known to be very inefficient anyways, so we don't target that.

> Another typical problem is the root ownership which will lead to a segfault if someone is not aware of that the histogram is owned by a TFile, which will delete the histogram upon closing. Also this behavior is not consistent with other interfaces like BCHistogramFitter which will copy the histogram, hence not showing the tfile closing problem.

Ok, I will just copy the histogram and everyone will be happy until the end of days, or even after destruction...
