### ISSUE TITLE
on MacOS BAT gives "rpath" err after upgrading to Sierra (10.12)

### ISSUE THREAD

**Issue by DingXuefeng** [bat/bat#186]
Hi, 

we are trying to install and run examples of BAT on Mac Sierra (10.12). and it's giving 

<img width="566" alt="picture_error" src="https://cloud.githubusercontent.com/assets/3205938/19276299/3937e33a-8fd6-11e6-9beb-61eabdffebe3.png">

error.

we checked that on Mac EI Capitan (10.11) it's working well.

we did some debug with `otool -L` on examples/basic/binomial package. here is the result:

on Sierra (where BAT does not run)
otool -L .libs/runEfficiency gives
<img width="696" alt="otool_sierra" src="https://cloud.githubusercontent.com/assets/3205938/19276690/7d2bee28-8fd7-11e6-9411-8c9184af3027.png">

otool -l .libs/runEfficiency  gives
[otool_ml_EICapitan.zip](https://github.com/bat/bat/files/522233/otool_ml_EICapitan.zip)

on EI Capitan (where BAT works where) 
otool -L .libs/runEfficiency gives
<img width="807" alt="otool_eicapitan" src="https://cloud.githubusercontent.com/assets/3205938/19276515/e356e564-8fd6-11e6-9fb2-5374d0b81e9e.png">
otool -l .libs/runEfficiency  gives

[otool_ml.zip](https://github.com/bat/bat/files/522232/otool_ml.zip)

it's strange that on Sierra BAT decided to use rpath, while LC_RPATH is not written in the executables.

at the same time, we found that it's possible to execute the .libs/runEfficiency directly without the wrapper, except some error shown. here is the output.
[Archive.zip](https://github.com/bat/bat/files/522252/Archive.zip)

could you help us identify the reason? btw do you have plans to port BAT to home-brew?

**Comment by oschulz** [comment]
We'll look into it - we may have to upgrade our test system to 10.12 first, though.

**Comment by oschulz** [comment]
> do you have plans to port BAT to home-brew?

Currently not: We'd need additional manpower - if we did homebrew, we should also provide (and test, etc.) Linux .deb and .rpm packages ...

If a volunteer wants to create and maintain a brew BAT package, we'd likely give our blessing, of course.

**Comment by greenwald** [comment]
I have recreated the bug. The solution from @dvandyk: Use rpath---

`AM_LDFLAGS = -Wl,-rpath,$(ROOTLIBDIR) -L$(ROOTLIBDIR)`

---edited directly in `Makefile-common.am` in examples (line 18). The same should also be done in the makefile for the test. I leave it up to @fredRos to implement the most elegant solution.

**Comment by fredRos** [comment]
We also have to update the installation instructions: if somebody build a library that depends on BAT, they too should use rpath instead of `LD_LIBRARY_PATH`. Apparently the rules for linking were changed 10 years ago but the common practice of modifying `LD_LIBRARY_PATH` was acceptable on mac os until now, and it's still ok on the linuxes I use

**Comment by dvandyk** [comment]
On MacOS it should probably be DYLD_LIBRARY_PATH anyway, see [here](http://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s). Maybe they do not recognize LD_LIBRARY_PATH as an alias of DYLD_LIBRARY_PATH? Also, LD_LIBRARY_PATH should always only be a temporary measure.

**Comment by fredRos** [comment]
yeah, we set or instruct the user to to `DYLD_LIBRARY_PATH`. wikipedia mentions that 

> The dynamic linker of the GNU C Library searches for shared libraries in the following locations:[1]
>
>   The (colon-separated) paths in the DT_RPATH dynamic section attribute of the binary if present and the DT_RUNPATH attribute does not exist.
>    The (colon-separated) paths in the environment variable LD_LIBRARY_PATH, unless the executable is a setuid/setgid binary, in which case it is ignored. 

so perhaps `setuid` bit is set on the mac and that prevents `LD_LIBRARY_PATH` from helping? In any case, to avoid loading another version of root than the one BAT was configured and built for, we should use `rpath`

**Comment by fredRos** [comment]
This issue is due to system integrity protections (SIP), a new feature on mac os since capitan. I'm a bit surprised we only noticed it now with Sierra. There are many other projects with exactly the same problem, for example from a year ago
https://github.com/oracle/node-oracledb/issues/231
http://apple.stackexchange.com/questions/215030/el-capitan-make-check-dyld-library-path

From what I gather, we can't just continue with `DYLD_LIBRARY_PATH` on the newest mac os without requiring hacks from the user. If need be, we could use rpath only there but I don't like the idea of different instructions on different platforms if we can have one solution that works in all places.

**Comment by oschulz** [comment]
> If need be, we could use rpath only there but I don't like the idea of different instructions on different platforms if we can have one solution that works in all places.

@fredRos: I'd rather argue that it would be strange to deviate from what is (to my knowledge) a widely used convention on Linux (no rpath), just because things have changed on OS-X. Cygwin, for example, doesn't seem to even support rpath (according to the sage conversation you mentioned). Sure, we don't currently target Cygwin, but it's still a hint that it might not be wise to change to rpath on all platforms. So I would only set it on OS-X.

It would be interesting to see how homebrew handles this. Do they inject rpath into package builds (I assume few packages will set it by default)?

**Comment by fredRos** [comment]
In order to reach a decision, let's aim for a compromise: rpath on mac os, `LD_LIBRARY_PATH` on linux. @oschulz do you volunteer to update my pr #195 to reflect what you see fit? You could even make this a `configure` option:
    
    ./configure --enable-rpath

and the default is set based on the operating system. This would localize the changes and give users extra flexibility. If they don't want to mess with `LD_LIBRARY_PATH` in linux, they can just use `rpath`.

**Comment by fredRos** [comment]
We now build BAT with rpath on Mac OS X and continue to use LD_LIBRARY_PATH on linux in the current master. Testing on Mac is more difficult as we can't build containers, so feedback is welcome if our fix helps
