### ISSUE TITLE
Fraction Fit-Parameter class

### ISSUE THREAD

**Issue by tquante** [bat/bat#201]
Dear Developers,

currently I working on a fit that includes several fractions. These fractions are used as scaling parameters 
as in the following example:

`B*f1 +B*f2 +B*(1-f1-f2)`

The main problem which arise is, that the sum of all fraction must be equal to 1. To overcome this problem  the likelihood returns nan in case the sum is above one. Due to the fact that Bat tries to find a valid likelihood before starting the prerun this results in a fit failure, if many fractions are involved. Increasing the number of tries helps a bit, but there are still too many MCMC steps which cannot be used, resulting in very long execution times.

Would it be possible to provide a class which registers all fractions to assure that the the sum of all fractions is 1 for each iteration? Or is there any interface, which I did not notice in BAT, that can be used for that?

Thanks for your help

**Comment by fredRos** [comment]
dear @tquante, am I right that a fraction in your equation is `f1` and `f2`? The general approach to this problem is to realize that the fractions are constrained to lie on the unit simplex. The stick breaking procedure allows you to draw a point on the simplex without generating invalid points.  See the attached pdf. 
[simplex.pdf](https://github.com/bat/bat/files/796878/simplex.pdf)

We did not implement this yet because it add some complexity to handling the parameters together. Let me know if this helps and if you think we can find a simple way to incorporate this in a general manner into bat
