### ISSUE TITLE
logpoisson lambda <= 0

### ISSUE THREAD

**Issue by fredRos** [bat/bat#216]
by email:

One of the problems I faced when setting things up were related to the lines

```c++
if (lambda <= 0) {
    BCLog::OutWarning("BCMath::LogPoisson : expectation value (lambda) cannot be negative!");
    return std::numeric_limits<double>::quiet_NaN();
}
```

in BCMath::LogPoisson. I was for certain bins sending in an expectation of lambda=0 (due to some truncation), and I was unfortunately sent on a wild-goose chase by the error message indicating that I was sending in negative numbers! If you want to disallow lambda=0 even when x=0, that's possibly OK, but at least the error message should not suggest that a negative number has been supplied to the function.

**Comment by fredRos** [comment]
Remember that the Poisson distribution is singular for `lambda=0`, so we can't accept that value. You are right about the misleading error message. But it is has already been fixed more than a year ago in the master branch https://github.com/bat/bat/commit/1f7cb4da53f2785066d35a78e590e46f133dc19a

I guess it's time to make a new release :smile:

**Comment by mkbugge** [comment]
OK, good that the error message will be fixed when there is a new release, but having thought more about this, I do not agree with your claim that lambda=0 should not be allowed. I guess you are worried about the case lambda=0 and x=0 and the corresponding factor lambda^x which will be 0^0, however, I think there are several ways to argue that the correct value is 1. The easiest is probably just remembering the meaning of the number we are working with: if observing a count resulting from a process with a rate of exactly 0, we will observe 0 counts always, so the probability for this observation is 1. 

You do not need to worry about taking log(0), because you already have the correct handling of the case x=0:

`if (x == 0.)
       return -lambda;`

If the user supplies lambda=0, the function will return 0 as it should (log(1)). In the case x>0, lambda=0 is also OK and corresponds to a probability of zero. Of course, when working with the log-likelihood this is a bit awkward, but can be handled in some reasonable way, like returning -inf or throwing an error. See for example treatment in RooStats (OK, there is some mistake in the comment, but the behaviour is correct):

`    if (mu<=0 && N>0) {

	// Catch error condition: data present where zero events are predicted
	logEvalError(Form("Observed %f events in bin %d with zero event yield",N,i)) ;
	
      } else if (fabs(mu)<1e-10 && fabs(N)<1e-10) {

	// Special handling of this case since log(Poisson(0,0)=0 but can't be calculated with usual log-formula
	// since log(mu)=0. No update of result is required since term=0.

      } else `

(see https://root.cern.ch/root/html534/RooNLLVar.html#RooNLLVar:evaluatePartition)

The current implementation will not work well together with BAT's very own BCMTF, I think, because there you have (as we had in our version) a truncation setting the expectation to zero whenever a large systematic uncertainty would drive a bin expectation negative:

`    // check if expectation is positive
       if (expectation < 0)
           expectation = 0.;
   
       return expectation;`

(from https://wwwold.mppmu.mpg.de/bat/docs/refman/html-1.0.0-RC1/BCMTF_8cxx_source.html line 550)

This is what caused me to observe the issue, although it is not a big problem for us since I now changed the truncation to something like 10^{-300} and because our baseline approach is in any case to use a log-normal systematics description which circumvents the issue more elegantly.

**Comment by fredRos** [comment]
> if observing a count resulting from a process with a rate of exactly 0, we will observe 0 counts always, so the probability for this observation is 1.

I agree. That's what I meant by singular: the probability distribution collapes into a single point `x=0`.

> You do not need to worry about taking log(0), because you already have the correct handling of the case x=0:
> if (x == 0.) return -lambda;

Ok but right now this check comes after checking `lambda == 0.`. In any case I'm not sure why poisson accepts `double x` instead of `unsigned x`. Probably this is convenient in template fits but it is not strictly speaking the definition of the Poisson distribution.

That aside, I agree that we should check explicitly for `lambda == 0.` and this should not result in a `NaN`. Thanks for hinting at the `BCMTF` implementation.

I created a pull request, please check that it conforms to what you need.

**Comment by mkbugge** [comment]
Looks good! Regarding the double vs. unsigned definition of x, my experience is that calculating "Asimov" results inserting expected background as data works as an excellent approximation to the background-only median results (i.e. "expected" results). Having x as unsigned would then lead to problems as all "data" would be rounded down, which with many bins can lead to a result far from the median.
