### ISSUE TITLE
rootcling does not support "--param=ssp-buffer-size=4" from CXXFLAGS in build

### ISSUE THREAD

**Issue by rknegjens** [bat/bat#24]
When running "make" for BAT 0.9.4.1 I get errors of the form:
```
/usr/bin/rootcling -f libBATmtf_rdict.cxx.tmp -s libBATmtf.so -rml libBATmtf.so -rmf libBATmtf.rootmap -c -D_FORTIFY_SOURCE=2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fopenmp -I/usr/include BCMTFAnalysisFacility.h BCMTFChannel.h BCMTFComparisonTool.h BCMTF.h BCMTFProcess.h BCMTFSystematic.h BCMTFSystematicVariation.h BCMTFTemplate.h LinkDef.h
Argument "--param=ssp-buffer-size=4" is not a supported cling argument. This could be mistyped rootcling argument. Please check the commandline.
```
By removing "--param=ssp-buffer-size=4" from CXXFLAGS (in all of the relevant Makefiles), BAT builds fine.

I'm running archlinux (3.19.2-1 kernel), ROOT 6 (git, master branch), i686 arch, gcc 4.9.2

**Comment by fredRos** [comment]
Dear Rob,

the option '--param =ssp-buffer-size=4' was used in building your root
library, and we just take over those options. For example in
`models/mtf/Makefile.am`:
    AM_CXXFLAGS= $(ROOTAUXCFLAGS) -Wall -fPIC -I$(top_srcdir) $(ROOTCFLAGS)

I see several options:

1. does the problem persist if you use root5?
2. we check if `rootcling` really needs those options. Seems it only
looks at class information and doesn't really compile, so any option
related to optimization, architecture, or buffer size is overkill. I
remember faintly that we passed on the flags because  `-std=c++11` is
needed if root was built that way.
3. we could write a patch that manually fixes your problem but that
clearly does not generalize

I'm in favor of 2., it seems to be the cleanest solution.

Fred

**Comment by rknegjens** [comment]
Dear Fred,
Thanks for getting to the bottom of my issue. I didn't have this issue with root5, but nonetheless prefer to continue using root6. I agree a specialized patch would be overkill, and that the cleanest solution would be not to feed unnecessary flags to rootcling. Perhaps the single  c++11 flag can be regexed for in ROOTCFLAGS and be added given conditionally to rootcling?
