### ISSUE TITLE
Save samples after fixed intervals at run time

### ISSUE THREAD

**Issue by fredRos** [bat/bat#48]
A user request:

I was wondering what you think about being able to write to file “on the fly”, e.g. after each n-th iteration/sample.
This would allow me (the user) to have a look at the chains after some time and still be able to keep it running for longer (if the conclusion is that it’s needed) -> flexibility.

**Comment by fredRos** [comment]
I agree this is a useful feature and shouldn't be hard to implement

**Comment by greenwald** [comment]
Not hard at all to implement since it's already in there.

We save the root file every time the progress message is printed. We autosave, I think, every number of bytes (preset by ROOT) during the prerun, too. We used to save every check of the prerun, but I did some timing tests and saw that this caused a huge slowdown after a while.

**Comment by greenwald** [comment]
I should add: we save the ROOT files with the "saveself" option. This means you can safely open the ROOT file and draw from the tree even while BAT continues to calculate and add to it.

**Comment by fredRos** [comment]
So this continuous saving is a new thing that wasn't available in 0.9.4?
@greenwald, are you ok with me adding an option to save more frequently
if the user so desires?

**Comment by greenwald** [comment]
Yes, it appears it's new since 0.9.4. I would suggest that we leave the ROOT file updating sync'ed to the progress output to the log, and allow the user to change that frequency if he desires. Another option is to let users set the option to the ROOT file for what interval of added bytes to the tree it self-saves.

I did timing tests, using ROOT's stopwatch and setting the calculation time as BCObservable (this works really well). And I saw slowing down which somehow has to do with ROOT's Autosave. This went away when I used the added-bytes determination of when to selfsave for the pre-run, and the update output frequency for selfsaving in the main run. I would leave the scheme as such.

We could think to make something in the test directory that does this timing test, in order to test that nothing we add has adverse effects.
