### ISSUE TITLE
Review defaults

### ISSUE THREAD

**Issue by greenwald** [bat/bat#83]
We need to review what we set as defaults.

**Comment by fredRos** [comment]
Do we want multivariate or factorized proposal? We agreed on multivariate.
Then, Gaussian or Cauchy? Cauchy was the default, but I hesitate to just make it the default for the multivariate case because I don't know of any suggestions on the 'optimal' acceptance in that case. For the Gaussian proposal and Gaussian target, it's 23.8% for large dimensions
